apiVersion: v1
kind: Service
metadata:
  labels:
    app: devplatform-usersvc
  name: devplatform-usersvc
  namespace: dev-platform
spec:
  selector:
    app: devplatform-usersvc
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
